// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDAtwwp8yyyUP0vk2e6fXyK8n4IhLV8dDU',
    appId: '1:1045743311657:android:3abbd853ca054f07df7538',
    messagingSenderId: '1045743311657',
    projectId: 'ecommerce-cb837',
    databaseURL: 'https://ecommerce-cb837.firebaseio.com',
    storageBucket: 'ecommerce-cb837.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAP8cmV64_xvEvoTGgjO1o7Mo_6SF3z85c',
    appId: '1:1045743311657:ios:13a3d72cfe2b2c58df7538',
    messagingSenderId: '1045743311657',
    projectId: 'ecommerce-cb837',
    databaseURL: 'https://ecommerce-cb837.firebaseio.com',
    storageBucket: 'ecommerce-cb837.appspot.com',
    iosClientId: '1045743311657-ih4s1tlcl8ubq1mp3tg8rlpbt5hue6p7.apps.googleusercontent.com',
    iosBundleId: 'com.example.tafweed',
  );
}
